import type { NextPage } from 'next';
import Head from 'next/head'
import React, { useRef, useState, useEffect } from 'react'

// Components
import Tabbar from '../components/tabbar';
import Footer from '../components/footer';

// Blog
import { getAllPosts } from '../lib/api'
import Post from '../interfaces/post'

type Props = {
  allPosts: Post[]
}

// Blog infos
export const getStaticProps = async () => {
  const allPosts = getAllPosts([
    'title',
    'date',
    'slug',
    'author',
    'excerpt',
  ])

  return {
    props: { allPosts },
  }
}

// Hook
function useWindowSize() {
  const [windowSize, setWindowSize] = useState({
    width: 0,
    height: 0,
  });

  useEffect(() => {
    if (typeof window !== 'undefined') {
      const resizeHandler = () => {
        setWindowSize({
          width: window.innerWidth,
          height: window.innerHeight,
        });
      };
      // Add event listener
      window.addEventListener("resize", resizeHandler);
      
      console.log(window.location.pathname)

      resizeHandler();
    
      // Remove event listener on cleanup
      return () => window.removeEventListener("resize", resizeHandler);
    }
  }, []); // Empty array ensures that effect is only run on mount
  return windowSize;
}

// Blog
const Blog: NextPage = () => {
  const windowSize = useWindowSize();
  return (
    <>
      <Head>
        <title>Roam's Blog</title>
        <meta name="description" content="Roamzhen's Blog Generated by Next" />
      </Head>

      {/* 顶部导航栏 */}
      <Tabbar />

      {/* 正文区域 */}
      <div className='wrap-content'>
        <div className='intro'>
        </div>
      </div>

      {/* 底部导航栏 */}
      <Footer />
    </>
  );
};

export default Blog
