import type { NextPage } from 'next';
import Head from 'next/head'
import React, { useRef, useState, useEffect } from 'react'
import * as THREE from 'three';
import { Canvas, useFrame, ThreeElements } from '@react-three/fiber'
import { OrbitControls } from "@react-three/drei"

// 3D
import Ground from '../components/ground';

// Blog
import { getAllPosts } from '../lib/api'
import Post from '../interfaces/post'

type Props = {
  allPosts: Post[]
}

// Blog infos
export const getStaticProps = async () => {
  const allPosts = getAllPosts([
    'title',
    'date',
    'slug',
    'author',
    'excerpt',
  ])

  return {
    props: { allPosts },
  }
}

// Hook
function useWindowSize() {
  const [windowSize, setWindowSize] = useState({
    width: 0,
    height: 0,
  });

  useEffect(() => {
    if (typeof window !== 'undefined') {
      const resizeHandler = () => {
        setWindowSize({
          width: window.innerWidth,
          height: window.innerHeight,
        });
      };
      // Add event listener
      window.addEventListener("resize", resizeHandler);
      
      resizeHandler();
    
      // Remove event listener on cleanup
      return () => window.removeEventListener("resize", resizeHandler);
    }
  }, []); // Empty array ensures that effect is only run on mount
  return windowSize;
}

function Box(props: ThreeElements['mesh']) {
  const mesh = useRef<THREE.Mesh>(null!)
  const [hovered, setHover] = useState(false)
  const [active, setActive] = useState(false)
  // useFrame((state, delta) => (mesh.current.rotation.x += 0.01))
  return (
    <mesh
      {...props}
      ref={mesh}
      scale={active ? 1.5 : 1}
      onClick={(event) => setActive(!active)}
      onPointerOver={(event) => setHover(true)}
      onPointerOut={(event) => setHover(false)}>
      <boxGeometry args={[1, 1, 1]} />
      <meshStandardMaterial color={hovered ? 'hotpink' : 'orange'} />
    </mesh>
  )
}

// Index
const Home: NextPage = () => {
  const windowSize = useWindowSize();
  return (
    <div className='main'>
      <Head>
        <title>Roam's Blog</title>
        <meta name="description" content="Roamzhen's Blog Generated by Next" />
      </Head>

      <div className='wrap-canvas'>
        <Canvas
          style={{width: windowSize.width, height: windowSize.height}}
          camera={{ position: [0, 30, 0], fov: 45, near: 0.1, far: 1000 }}
        >
          <ambientLight />
          <Ground position={[0, 0, 0]} />
          <OrbitControls
            target={[0, 0, 0]}
            autoRotate={true}
            autoRotateSpeed={10}
          />
        </Canvas>
      </div>

      <div className='wrap-cover'>
        <div className='intro'>
          <h2 className='big'><span>Hello</span></h2>
          <h2><span>How's it going?</span><span>My name is Roam</span></h2>
        </div>
      </div>
    </div>
  );
};

export default Home
