import type { NextPage } from 'next';
import Head from 'next/head'
import React, { useRef, useState, useEffect } from 'react'
import * as THREE from 'three';
import { Canvas, useFrame, ThreeElements } from '@react-three/fiber'

// Components
import Tabbar from '../components/tabbar';
import Footer from '../components/footer';

// custom components
import Greeting from '../components/greeting';

// 3D
import Ground from '../components/ground';

// Blog
import { getAllPosts } from '../lib/api'
import Post from '../interfaces/post'

type Props = {
  allPosts: Post[]
}

// Blog infos
export const getStaticProps = async () => {
  const allPosts = getAllPosts([
    'title',
    'date',
    'slug',
    'author',
    'excerpt',
  ])

  return {
    props: { allPosts },
  }
}

// Hook
function useWindowSize() {
  const [windowSize, setWindowSize] = useState({
    width: 0,
    height: 0,
  });

  useEffect(() => {
    if (typeof window !== 'undefined') {
      const resizeHandler = () => {
        setWindowSize({
          width: window.innerWidth,
          height: window.innerHeight,
        });
      };
      // Add event listener
      window.addEventListener("resize", resizeHandler);
      

      console.log(window.location.pathname)
      
      resizeHandler();
    
      // Remove event listener on cleanup
      return () => window.removeEventListener("resize", resizeHandler);
    }
  }, []); // Empty array ensures that effect is only run on mount
  return windowSize;
}

// Index
const Home: NextPage = () => {
  const windowSize = useWindowSize();
  return (
    <>
      <Head>
        <title>Roam Ye</title>
        <meta name="description" content="Roamzhen's Blog Generated by Next" />
      </Head>

      {/* 顶部导航栏 */}
      <Tabbar />

      {/* 三维背景 */}
      <div className='wrap-canvas'>
        <Canvas
          style={{width: windowSize.width, height: windowSize.height}}
          camera={{ position: [0, 30, 0], fov: 45, near: 0.1, far: 1000 }}
        >
          <ambientLight />
          <Ground position={[0, 0, 0]} />
        </Canvas>
      </div>

      {/* 正文区域 */}
      <article className='container max-w-screen-lg mx-auto'>
        <section className='intro font-serif py-10'>
          <div className="space-y-4">
            <Greeting className='text-changing' interval={4000} />
            <p className="text-2xl">
              I'm<span className="font-bold px-2">Ye Zhenpeng</span>, you can also call me<span className="font-bold px-2">Roam</span>.
            </p>
            <p className="text-2xl font-medium">
              A Senior Developer specializing on 3D Graphics Rendering, AI integration and cross-platform Application development.
            </p>
            <p className="text-xl">
              Currently working in the WeChat Mini Program team at Tencent, previously worked at Alibaba TaoBao, Tencent ISUX, Netease.
            </p>
            <p className="mt-8 text-xl leading-relaxed">
              <span className="font-bold text-gray-900 block mb-2">What I've done</span>
            </p>
            <p className="mt-8 text-lg leading-relaxed">
              <span className="font-bold text-gray-900 block mb-2">Tencent WeChat Mini Program</span>
            </p>
            <p className="mt-4 text-lg leading-relaxed text-gray-700">
              In 3D graphics, I architected the development of the xr-frame framework's rendering system, implementing a complete PBR rendering pipeline and developed corresponding rendering logic for different platforms (mobile OpenGL, Vision Pro Metal, Meta Quest WebGPU).
            </p>
            <p className="mt-4 text-lg leading-relaxed text-gray-700">
              In Game engine, I was one of the main developers of the WeChat Mini Game Engine, I was responsible for developing the 2D system, implementing complete rendering, layout, and interaction capabilities.
              Through technical innovations like shared memory optimization and render batching, the engine achieved performance levels 4 times faster than CocosCreator.
              The engine has successfully supported the porting of multiple large Unity games, including Tianlong Babu Honor Edition.
            </p>
            <p className="mt-4 text-lg leading-relaxed text-gray-700">
              In AI applications, I developed intelligent tools based on LLM and computer vision, including a Mini Program transaction page information extraction system
              and an OpenCV-based intelligent ad adaptation system, significantly improving business efficiency.
            </p>
            <p className="mt-8 text-lg leading-relaxed">
              <span className="font-bold text-gray-900 block mb-2">Alibaba TaoBao</span>
              I worked on imgcook, an AI-powered platform that transforms design mockups into code using computer vision and OCR.
            </p>

          </div>

        </section>
       
      </article>

      {/* 底部导航栏 */}
      <Footer />
    </>
  );
};

export default Home
