import type { NextPage } from 'next';
import Head from 'next/head'
import React, { useRef, useState, useEffect } from 'react'

// Components
import Tabbar from '../components/tabbar';
import Footer from '../components/footer';

// LABS
const LABS: NextPage = () => {
  return (
    <>
      <Head>
        <title>Roam's Labs</title>
        <meta name="description" content="Roamzhen's Blog Generated by Next" />
      </Head>

      {/* 顶部导航栏 */}
      <Tabbar />

      {/* 正文区域 */}
      <div className='wrap-content'>
        <div className='intro'>
        </div>
      </div>

      {/* 底部导航栏 */}
      <Footer />
    </>
  );
};

export default LABS
